[General]
bypass-system = true
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
private-ip-answer = true
dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true
dns-server = https://dns.google/dns-query, https://dns.adguard-dns.com/dns-query, cloudflare-dns.com, dns.quad9.net, dns.adguard-dns.com, dns.comss.one
fallback-dns-server = system
hijack-dns = :53
always-real-ip = *.lan,*.local
icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/camuigu/shadowsocks/main/shadowrocket-ru-exclude.conf

[Rule]
DOMAIN-SUFFIX,local,DIRECT
DOMAIN-SUFFIX,localhost,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT

DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,рф,DIRECT
DOMAIN-SUFFIX,su,DIRECT
DOMAIN-SUFFIX,by,DIRECT
DOMAIN-SUFFIX,xn--p1ai,DIRECT

DOMAIN-KEYWORD,yandex,DIRECT
DOMAIN-KEYWORD,avito,DIRECT
DOMAIN-KEYWORD,rambler,DIRECT
DOMAIN-KEYWORD,sberbank,DIRECT
DOMAIN-KEYWORD,tinkoff,DIRECT
DOMAIN-KEYWORD,alfabank,DIRECT
DOMAIN-KEYWORD,gazprom,DIRECT
DOMAIN-KEYWORD,rostelecom,DIRECT
DOMAIN-KEYWORD,beeline,DIRECT
DOMAIN-KEYWORD,megafon,DIRECT
DOMAIN-KEYWORD,lenta,DIRECT
DOMAIN-KEYWORD,interfax,DIRECT

DOMAIN-SUFFIX,dion.vc,DIRECT
DOMAIN-SUFFIX,dion.me,DIRECT
DOMAIN-SUFFIX,rbc.group,DIRECT
DOMAIN-SUFFIX,riaru.online,DIRECT
DOMAIN-SUFFIX,vk.com,DIRECT
DOMAIN-SUFFIX,.prod,DIRECT
DOMAIN-SUFFIX,.srv,DIRECT

GEOIP,RU,DIRECT
RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/refs/heads/main/rules/domains_geo_detect.list,DIRECT

# Все остальное через прокси
FINAL,PROXY

[Host]
localhost = 127.0.0.1
